### ISSUE TITLE
Data Source Paths May Not Be Being Parsed Correctly

### ISSUE THREAD

**Issue by backXslash** [marcogiusti/adsdb3#1]
The library certainly works as advertised (thank you **so** much for it, by the way).

However, every time I try to actually run a _real_ query (not a scalar function or something), it throws a 7041 error (File not found).

Naturally, I've checked, and the file is certainly there. The only difference I can see between the output I'm seeing and a working query execution in Advantage Data Architect is that the Data Source is being presented with double quotes like this:

```
CRIT:0000:root: Uncaught exception (in thread 140475410546816).
│ Traceback (most recent call last):
│   File "/pycharm_projects/faeb/testing/testing_lab.py", line 46, in <module>
│     cursor.execute("SELECT MAX(\"DATE\") FROM items;")
│   File "/usr/local/lib/python3.6/site-packages/adsdb3-0.2.0-py3.6-linux-x86_64.egg/adsdb3.py", line 524, in execute
│     parameters
│   File "/usr/local/lib/python3.6/site-packages/adsdb3-0.2.0-py3.6-linux-x86_64.egg/adsdb3.py", line 493, in _execute
│     stmt.execute()
│   File "/usr/local/lib/python3.6/site-packages/adsdb3-0.2.0-py3.6-linux-x86_64.egg/adsdb3.py", line 605, in execute
│     raise DatabaseError(*_error(self.handler))
│ adsdb3.DatabaseError: (7041, 'Error 7200:  AQE Error:  State = HY000;   NativeError = 7041;  [iAnywhere Solutions][Advantage SQL][ASA] Error 7041:  File not found.  Verify the specified path and file name is correct.  \\10.0.1.12:6262\\mnt\\hdd1tb\\Tables\\items.dbf Table name: items')
Segmentation fault

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Here's the entire script I'm using to test the connection / library:
```
import logging
import mondrian
from contextlib import closing
import adsdb3

functions_logger = logging.getLogger()
mondrian.setup(excepthook=True)
functions_logger.setLevel(logging.INFO)

conn_string = ("Data Source=\\10.0.1.12:6262\mnt\hdd1tb\Tables;" +
               "User ID=REDACTED;Password=REDACTED;ServerType=LOCAL;TrimTrailingSpaces=TRUE;CommType=TCP_IP;" +
               "Compression=NEVER;DbfsUseNulls=TRUE;LockMode=COMPATIBLE;" +
               "SecurityMode=IGNORERIGHTS;Shared=TRUE;ShowDeleted=FALSE;" +
               "TableType=VFP;TrimTrailingSpaces=TRUE;Pooling=TRUE;")

connection = adsdb3.connect(connection_string=conn_string)
cursor = connection.cursor()

cursor.execute("SELECT MAX(\"DATE\") FROM items;")
print(cursor.fetchone())

closing(cursor)
closing(connection)
exit(1)
```

This is as opposed to using **"EXECUTE PROCEDURE sp_mgGetInstallInfo();"** as the query, which produces the following:
```
('', '', 5, '11.10.0.24', '', '', 'Engl(Amer)', 'USA', 0, 5, 0)
Segmentation fault

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Any ideas about what may be wrong? Or maybe what's causing that segfault?

**Comment by marcogiusti** [comment]
Thank you @backXslash for using this library and congratulations, this is the first bug report.

About the file not found error, I remarked you use spaces with some option. I do not know how this is interpreted by the library, but in the documentation all the options are a single word "DataSource" rather than "Data Source". I think the problem origins from how python interprets the character preceded by a backslash `\`. Can you please try to prepend your strings with the `r` character to avoid the extra interpretation? Ex:

```
conn_string = (
    r"Data Source=\\10.0.1.12:6262\mnt\hdd1tb\Tables;"
    r"User ID=REDACTED;Password=REDACTED;ServerType=LOCAL;TrimTrailingSpaces=TRUE;CommType=TCP_IP;"
    r"Compression=NEVER;DbfsUseNulls=TRUE;LockMode=COMPATIBLE;"
    r"SecurityMode=IGNORERIGHTS;Shared=TRUE;ShowDeleted=FALSE;"
    r"TableType=VFP;TrimTrailingSpaces=TRUE;Pooling=TRUE;"
)
```

What worry me the most is the segfault. If this solves the problem with the missing file, can you please open a new report for the SIGSEGV?

Thanks

**Comment by backXslash** [comment]
That was 100% the issue and solved both the query issue and the segfault.

Now for the million dollar question - any idea if there's a SQLAlchemy dialect that's compatible with ADS?

**Comment by marcogiusti** [comment]
> Now for the million dollar question - any idea if there's a SQLAlchemy dialect that's compatible with ADS?

No, I am sorry.
